var = input('Digite algo: ')
print('O tipo é: ', type(var))
print('É somente espaços?', var.isspace())
print('é um numero?', var.isnumeric())
print('é alfabetico?', var.isalpha())
print('é alfanumerico?', var.isalnum())
print('esta em maiúsculas?', var.isupper())
print('esta em minuscula?', var.islower())
print('está capitalizada?', var.istitle())
